### ISSUE TITLE
My bot stopped handling and receive updates.

### ISSUE THREAD

**Issue by ihatemyself0** [2ei/tgram#15]
after 3 days of running my bot, it's stopped responding without any exceptions or any information in logger.

**Comment by 2ei** [comment]
attach more information to your issue or close it, i can't guess what happened to your bot, my magical power is limited.

**Comment by 2ei** [comment]
i will take a look for this..

**Comment by 2ei** [comment]
Should be [fixed](https://github.com/2ei/tgram/commit/754c7193d610104af4c9677894661a1e939c4a68), please reopen it if you faced it again.
